## Authorizations
# Uncomment out the merging for each enviornment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# enviornment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin

## Enviornments

development:
  host: 10.10.40.10
  port: 636
  attribute: sAMAccountName
  base: ou=Lanzatech Users, dc=lt,dc=local​
  admin_user: <%= ENV['LDAP_LOGIN'] %>
  admin_password: <%= ENV['LDAP_PASSWORD'] %>
  ssl: true
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: false
  # <<: *AUTHORIZATIONS

production:
  host: 10.10.40.10
  port: 636
  attribute: sAMAccountName
  base: ou=Lanzatech Users, dc=lt,dc=local​
  admin_user: <%= ENV['LDAP_LOGIN'] %>
  admin_password: <%= ENV['LDAP_PASSWORD'] %>
  ssl: true
  # <<: *AUTHORIZATIONS